const paragraphs = document.querySelectorAll('.description');
paragraphs.forEach(addSpaces);

function addSpaces(p) {
  // Use innerHTML to see the <br /> tags generated by PHP's nl2br
  const originalHTML = p.innerHTML.trim();
  if (!originalHTML) return;

  const limit = 50; // Character limit per word

  // 1. Split the content into an array of lines based on <br> tags
  // This regex handles <br>, <br/>, and <br >
  const lines = originalHTML.split(/<br\s*\/?>/i);

  const processedLines = lines.map(line => {
    // 2. Split each line into individual words
    const words = line.split(' ');

    const processedWords = words.map(word => {
      // 3. If a word is longer than 15 chars, break it up
      if (word.length > limit) {
        const regex = new RegExp('.{1,' + limit + '}', 'g');
        const chunks = word.match(regex);
        return chunks ? chunks.join(' ') : word;
      }
      return word;
    });

    // Join words back into a line    //processedWords is an array of words after processing
    return processedWords.join(' '); //here  ' ' is used to join words with a space after processing and return the line
  });

  // 4. Re-join the lines with <br> tags and update the element
  p.innerHTML = processedLines.join('<br>');
}


// Run the function when the window finishes loading 
// (Necessary because we need to know the actual height of images)
window.addEventListener('load', () => {
    const images = document.querySelectorAll('#main-content .post-content img');

    images.forEach(img => {
        const container = img.parentElement;

        // Check if the image height is less than its container height
        if (img.clientHeight < container.clientHeight) {
            // Apply your specific design styles
            img.style.width = '100%';
            img.style.height = '100%';
            img.style.objectFit = 'cover';
            
            // Optional: Ensure the container doesn't have overflow issues
            container.style.overflow = 'hidden';
        }
    });
});