//Toggle Menubar

document.addEventListener("DOMContentLoaded", function () {
  const toggleBtn = document.getElementById('menu-toggle-btn');
  const mainMenu = document.getElementById('main-menu');
  const overlay = document.getElementById('menu-overlay');

  function toggleMenu() {
    mainMenu.classList.toggle('show');
    overlay.classList.toggle('active');
    toggleBtn.classList.toggle('pushed');

    if (mainMenu.classList.contains('show')) {
      document.body.style.overflow = 'hidden';
    } else {
      document.body.style.overflow = 'auto';
    }
  }

  if (toggleBtn) {
    toggleBtn.addEventListener('click', function (e) {
      e.stopPropagation();
      toggleMenu();
    });
  }

  if (overlay) {
    overlay.addEventListener('click', toggleMenu);
  }
});











//Paragraph Arrangement (Handle If Ckeditor is not used )
// const paragraphs = document.querySelectorAll('.description');
// paragraphs.forEach(addSpaces);

// function addSpaces(p) {
//   // Use innerHTML to see the <br /> tags generated by PHP's nl2br
//   const originalHTML = p.innerHTML.trim();
//   if (!originalHTML) return;

//   const limit = 50; // Character limit per word

//   // 1. Split the content into an array of lines based on <br> tags
//   // This regex handles <br>, <br/>, and <br >
//   const lines = originalHTML.split(/<br\s*\/?>/i);

//   const processedLines = lines.map(line => {
//     // 2. Split each line into individual words
//     const words = line.split(' ');

//     const processedWords = words.map(word => {
//       // 3. If a word is longer than 15 chars, break it up
//       if (word.length > limit) {
//         const regex = new RegExp('.{1,' + limit + '}', 'g');
//         const chunks = word.match(regex);
//         return chunks ? chunks.join(' ') : word;
//       }
//       return word;
//     });

//     // Join words back into a line    //processedWords is an array of words after processing
//     return processedWords.join(' '); //here  ' ' is used to join words with a space after processing and return the line
//   });

//   // 4. Re-join the lines with <br> tags and update the element
//   p.innerHTML = processedLines.join('<br>');
// }




// Run the function when the window finishes loading 
// (Necessary because we need to know the actual height of images)
window.addEventListener('load', () => {
  const images = document.querySelectorAll('#main-content .post-content img');

  images.forEach(img => {
    const container = img.parentElement;

    // Check if the image height is less than its container height
    if (img.clientHeight < container.clientHeight) {
      // Apply your specific design styles
      img.style.width = '100%';
      img.style.height = '100%';
      img.style.objectFit = 'cover';

      // Optional: Ensure the container doesn't have overflow issues
      container.style.overflow = 'hidden';
    }
  });
});




/**
 * Add image from library
 */

// 1. Handle File Upload Preview
function previewFile() {
  const fileInput = document.getElementById('imageInput');
  const preview = document.getElementById('preview');
  const previewText = document.getElementById('previewText');
  const removeBtn = document.getElementById('removeBtn');
  const hiddenInput = document.getElementById('selected_image_input');

  // Clear gallery selection if file is uploaded
  hiddenInput.value = "";

  const file = fileInput.files[0];
  if (file) {
    const reader = new FileReader();
    reader.onload = function (e) {
      preview.src = e.target.result;
      preview.style.display = 'block';
      previewText.style.display = 'none';
      removeBtn.style.display = 'block';
    }
    reader.readAsDataURL(file);
  }
}

// 2. Handle Gallery Selection
function selectMedia(path) {
  const fileInput = document.getElementById('imageInput');
  const hiddenInput = document.getElementById('selected_image_input');
  const preview = document.getElementById('preview');
  const previewText = document.getElementById('previewText');
  const removeBtn = document.getElementById('removeBtn');

  // Clear file input
  fileInput.value = "";

  // Set hidden input value
  hiddenInput.value = path;

  // Update preview
  preview.src = path; // Ensure this path is correct relative to admin folder
  preview.style.display = 'block';
  previewText.style.display = 'none';
  removeBtn.style.display = 'block';

  // Close modal
  // Using vanilla JS to close bootstrap modal if jQuery is not available
  const modalEl = document.getElementById('mediaModal');
  const modal = bootstrap.Modal.getInstance(modalEl);
  if (modal) {
    modal.hide();
  }
}

// 3. Clear Selection
function clearImageSelection() {
  document.getElementById('imageInput').value = "";
  document.getElementById('selected_image_input').value = "";

  document.getElementById('preview').src = "#";
  document.getElementById('preview').style.display = 'none';
  document.getElementById('previewText').style.display = 'block';
  document.getElementById('removeBtn').style.display = 'none';
}

// 4. Form Validation
function validateImage() {
  const fileVal = document.getElementById('imageInput').value;
  const galleryVal = document.getElementById('selected_image_input').value;

  if (fileVal === "" && galleryVal === "") {
    alert("⚠️ Please select a Featured Image!\nUpload a new one OR choose from the library.");
    return false;
  }
  return true;
}
